name: 'google-drive-upload-action'
description: 'Upload files to Google Drive'
author: 'Mateusz Borycki'
inputs:
  credentials:
    description: 'the service account credentials encoded in base64'
    required: true
  filename:
    description: 'the name of the file you want to upload'
    required: true
  folderId:
    description: 'the Id of the parent folder you want to upload the file in'
    required: true
  driveId:
    description: 'the Id of the drive'
    required: false
  name:
    description: 'what you want the file to be called in Google Drive'
    required: false
  mimeType:
    description: 'file MimeType. If absent, Google Drive will attempt to automatically detect an appropriate value'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
