name: 'google-drive-upload-action'
description: 'Upload files to Google Drive'
author: 'Mateusz Borycki'
inputs:
  credentials:
    description: 'the service account credentials encoded in base64'
    required: true
  filePath:
    description: 'path to file that you want to upload'
    required: true
  folderId:
    description: 'the Id of the parent folder you want to upload the file in'
    required: true
  driveId:
    description: 'the Id of the drive'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
